export enum Decision {
    SUPPRIMER_POSTE = 'SUPPRIMER_POSTE',
    SUPPRIMER_COMMENTAIRE = 'SUPPRIMER_COMMENTAIRE',
    BLOQUER_UTILISATEUR = 'BLOQUER_UTILISATEUR',
    SUPPRIMER_BLOQUER = 'SUPPRIMER_BLOQUER',
    NE_RIEN_FAIRE = 'NE_RIEN_FAIRE'
  }